# Generated by Django 2.2.7 on 2019-11-09 01:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AgencyModel',
                'verbose_name_plural': 'AgencyModels',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('category', models.PositiveSmallIntegerField(default=3, verbose_name='category')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_hoteles', to='backhotel.AgencyModel')),
            ],
            options={
                'verbose_name': 'HotelModel',
                'verbose_name_plural': 'HotelModels',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('room_type', models.CharField(max_length=50, verbose_name='type')),
                ('base_price', models.PositiveIntegerField(verbose_name='price')),
                ('tax', models.PositiveIntegerField(verbose_name='% tax')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='backhotel.HotelModel')),
            ],
            options={
                'verbose_name': 'RoomModel',
                'verbose_name_plural': 'RoomModels',
            },
        ),
    ]
