# Generated by Django 2.2.7 on 2019-11-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backhotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('tax', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_imported', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival', models.DateField(blank=True, null=True)),
                ('deperture', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BookingModel',
                'verbose_name_plural': 'BookingModels',
            },
        ),
        migrations.AlterModelOptions(
            name='hotelmodel',
            options={'ordering': ('id',), 'verbose_name': 'HotelModel', 'verbose_name_plural': 'HotelModels'},
        ),
        migrations.AlterModelOptions(
            name='roommodel',
            options={'ordering': ('id',), 'verbose_name': 'RoomModel', 'verbose_name_plural': 'RoomModels'},
        ),
        migrations.CreateModel(
            name='PaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('born_date', models.DateField()),
                ('genre', models.PositiveIntegerField(choices=[(0, 'No spec'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0)),
                ('doc_type', models.PositiveIntegerField(choices=[(1, 'NID'), (2, 'Passport')], default=2)),
                ('doc_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_pax', to='backhotel.BookingModel')),
            ],
            options={
                'verbose_name': 'PaxModel',
                'verbose_name_plural': 'PaxModels',
            },
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='backhotel.RoomModel'),
        ),
    ]
